---
abstract: 'Base class and script for Schema deploy.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  DBIx::Class::Core: 0
  DBIx::Class::InflateColumn::DateTime: 0
  DBIx::Class::Schema: 0
  English: 0
  ExtUtils::MakeMaker: 6.59
  File::Object: 0
  File::Spec::Functions: 0
  File::Temp: 0
  IO::Barf: 0
  SQL::Translator: 0.11018
  Schema::Abstract: 0.03
  Test::More: 0
  Test::NoWarnings: 0
  Test::Output: 0
  Test::Warn: 0.31
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Schema-Deploy
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  English: 0
  Error::Pure: 0
  Getopt::Std: 0
  perl: 5.6.0
resources:
  bugtracker: https://github.com/michal-josef-spacek/App-Schema-Deploy/issues
  homepage: https://github.com/michal-josef-spacek/App-Schema-Deploy
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/App-Schema-Deploy
version: '0.06'
